spring:
  application:
    name: crypto-data
  kafka:
    consumer:
      bootstrap-servers: my-cluster-kafka-bootstrap.default.svc:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      uri: mongodb://adminuser:password123@10.43.246.249:27017/admin
    redis:
      host: redis-service.redis.svc.cluster.local # 10.43.133.15
      port: 6379
  influx:
    url: http://influxdb-service.default.svc.cluster.local:8086
    bucket: crypto
    org: xavelo.com
    token: rRfGF0-quQ8bkjlXxaS_qzCK0VVG_-jj3h47AnndP05D_-3ElKhdI86gnyzGiikBZPn6fDt-g4oF2577BJ4RKA== 
  metrics:
    export:
      prometheus:
        enabled: true
  web:
    exposure:
      include: "*"
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info,metrics"
  endpoint:
    prometheus:
      enabled: true
  export:
    influx:
      enabled: true
      bucket: ${spring.influx.bucket}
      org: ${spring.influx.org}
      token: ${spring.influx.token}
      uri: ${spring.influx.url}
  