spring:
  application:
    name: crypto-data
  kafka:
    consumer:
      bootstrap-servers: my-cluster-kafka-bootstrap.default.svc:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      uri: mongodb://adminuser:password123@10.43.246.249:27017/admin
  redis:
    host: 10.43.133.15
    port: 6379
  metrics:
    export:
      prometheus:
        enabled: true
  web:
    exposure:
      include: "*"
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info,metrics"  # Expose the Prometheus endpoint
  endpoint:
    prometheus:
      enabled: true  # Enable the Prometheus endpoint
  