apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-data-deployment
  annotations:
    commitID: "f930c149781eb67d63c9b7c0d910c7c4b45b8636"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-data
    spec:
      containers:
        - name: crypto-data
          image: 'xavelo/crypto-data:f930c149781eb67d63c9b7c0d910c7c4b45b8636'
          ports:
            - containerPort: 80
