apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-data-deployment
  annotations:
    commitID: "532cac16f8a4bdca33583d16ef340813dd1b6d3b"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: crypto-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-data
    spec:
      containers:
        - name: crypto-data
          image: 'xavelo/crypto-data:532cac16f8a4bdca33583d16ef340813dd1b6d3b'
          ports:
            - containerPort: 80
