apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-data-deployment
  annotations:
    commitID: "df5fef73058ab1650077491db0fa52cfd0765fc1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-data
    spec:
      containers:
        - name: crypto-data
          image: 'xavelo/crypto-data:df5fef73058ab1650077491db0fa52cfd0765fc1'
          ports:
            - containerPort: 80
