apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-data-deployment
  annotations:
    commitID: "4dae90ec9f4c1aacab4dde3a365ae7029c959b85"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-data
    spec:
      containers:
        - name: crypto-data
          image: 'xavelo/crypto-data:4dae90ec9f4c1aacab4dde3a365ae7029c959b85'
          ports:
            - containerPort: 80
