apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-data-deployment
  annotations:
    commitID: "8f8a3dac04fce9c50a3da8eabc869d9cca1a364b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-data
    spec:
      containers:
        - name: crypto-data
          image: 'xavelo/crypto-data:8f8a3dac04fce9c50a3da8eabc869d9cca1a364b'
          ports:
            - containerPort: 80
