apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-data-deployment
  annotations:
    commitID: "a624d3e423e7b157fa0507d97cc958ce950537fb"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: crypto-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-data
    spec:
      containers:
        - name: crypto-data
          image: 'xavelo/crypto-data:a624d3e423e7b157fa0507d97cc958ce950537fb'
          ports:
            - containerPort: 80
