apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-data-deployment
  annotations:
    commitID: "b7e7c8a2adbbd85c350305057907743aa4d257ac"
spec:
  #replicas: 4
  selector:
    matchLabels:
      app: crypto-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-data
    spec:
      containers:
        - name: crypto-data
          image: 'xavelo/crypto-data:b7e7c8a2adbbd85c350305057907743aa4d257ac'
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m" # Request 250 millicores (0.25 CPU)
            limits:
              cpu: "500m" # Limit at 500 millicores (0.5 CPU)
