apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-data-deployment
  annotations:
    commitID: "92c4cc8533164ff394ecd44c83bbd82943eff48d"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-data
    spec:
      containers:
        - name: crypto-data
          image: 'xavelo/crypto-data:92c4cc8533164ff394ecd44c83bbd82943eff48d'
          ports:
            - containerPort: 80
