apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-data-deployment
  annotations:
    commitID: "d6da4b858f494404e0db45e344bdb89f12d70549"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-data
    spec:
      containers:
        - name: crypto-data
          image: 'xavelo/crypto-data:d6da4b858f494404e0db45e344bdb89f12d70549'
          ports:
            - containerPort: 80
