apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-data-deployment
  annotations:
    commitID: "df3ba7015e0b3aadcb47d479bbe7d56e1de423dd"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-data
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crypto-data
    spec:
      containers:
        - name: crypto-data
          image: 'xavelo/crypto-data:df3ba7015e0b3aadcb47d479bbe7d56e1de423dd'
          ports:
            - containerPort: 80
